/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exangefilep2p;

import java.awt.event.ActionEvent;

/**
 *
 * @author dav
 */
public class ExangeFileP2P extends javax.swing.JFrame  implements MyGUI {
    private NetworkToolsImpl currentNetworkTools;

   /**
     *
     * @param nameFile
     * @param узел 
     * @return возвращает имя фай
     */
    @Override
    public String saveFile(String nameFile, Node myNode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    // ACTION
    public class ActionRefresh extends javax.swing.AbstractAction  {
        /**
         *
         * @throws IOException
         */
        public ActionRefresh() 
        {
            //super(java.util.ResourceBundle.getBundle("autoshutdown/Bundle").getString("textOption"),null);
            javax.swing.ImageIcon myIcon = null;
            /*try {
                myIcon = getIconFromImage(ImageIO.read((getClass().getResource("image/image_options.png"))));
            } catch (IOException ex) {
                Logger.getLogger(GeneralFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.putValue(SMALL_ICON, myIcon);*/
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            // this we do refresh
            
        }
    }
    
    public class SendUnit extends javax.swing.AbstractAction  {
        /**
         *
         * @throws IOException
         */
        public SendUnit() 
        {
            //super(java.util.ResourceBundle.getBundle("autoshutdown/Bundle").getString("textOption"),null);
            javax.swing.ImageIcon myIcon = null;
            /*try {
                myIcon = getIconFromImage(ImageIO.read((getClass().getResource("image/image_options.png"))));
            } catch (IOException ex) {
                Logger.getLogger(GeneralFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.putValue(SMALL_ICON, myIcon);*/
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            // this we send file or folder
            
        }
    }
    
    // END OF ACTION
    
    private void myInit(){
        currentNetworkTools = NetworkToolsFactory.getInstant().getNetworkTools();
    }
    /**
     * Creates new form NewJFrame
     */
    public ExangeFileP2P() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExangeFileP2P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExangeFileP2P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExangeFileP2P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExangeFileP2P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExangeFileP2P().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
